version: "1.0"
layer: bronze
database: microsoft
view: calendar_event_raw

source:
  bucket: main-data
  path: microsoft/calendar_event

description: "microsoft calendar_event data"
tags:
  - bronze
  - microsoft
  - calendar_event
  - auto-schema