# -*- coding: utf-8 -*-
"""cleansing_transformation_dag_to_deltalake.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12FEM-kr6nvdrpGaLllJp-Fl2f66g-eOo

Airflow DAG: cleansing_transformation_dag

Author: Lavanya Kalla

Description:
------------
This DAG performs data cleansing and transformation on raw CSV files
after schema validation (Subtask 2- DHAP-15). The output is a set of cleaned
datasets in a staging folder, ready for further processing
(conversion to Delta Lake in Subtask 4).

Key objectives:
---------------
1. Type coercion (convert string dates, numeric columns, etc.)
2. Null handling for required fields
3. Column normalization (e.g., lowercase column names, strip whitespace)
4. Filtering invalid or irrelevant records
5. Deduplication
6. Timezone normalization (convert date/time columns to UTC)
7. Save cleaned files to a staging directory
"""

import pandas as pd
import os
from datetime import datetime
from airflow.models.dag import DAG
from airflow.operators.python import PythonOperator
from airflow.operators.trigger_dagrun import TriggerDagRunOperator
from airflow.exceptions import AirflowException

# Defines the source directory for raw data within the Airflow container.
RAW_DATA_PATH = '/opt/airflow/data'
# Defines the target directory for cleaned data to be staged.
CLEANED_DATA_PATH = '/opt/airflow/data/cleaned'

# A list of all CSV files that this DAG is responsible for processing.
CSV_FILES = [
    'lead_log.csv',
    'paid_transactions.csv',
    'referral_rewards.csv',
    'user_logs.csv',
    'user_referral_logs.csv',
    'user_referral_statuses.csv',
    'user_referrals.csv'
]

def clean_lead_log(input_file, output_file):
    """
    Cleans the lead_log.csv file by dropping nulls and duplicates,
    and standardizing the date format.
    """
    if not os.path.exists(input_file):
        raise AirflowException(f"Input file not found: {input_file}")

    df = pd.read_csv(input_file)
    initial_rows = len(df)
    df.dropna(subset=['id', 'lead_id', 'created_at'], inplace=True)
    rows_after_na = len(df)
    df.drop_duplicates(inplace=True)
    rows_after_duplicates = len(df)
    df['created_at'] = pd.to_datetime(df['created_at'], utc=True)
    df.to_csv(output_file, index=False)

    na_dropped = initial_rows - rows_after_na
    duplicates_dropped = rows_after_na - rows_after_duplicates
    print(f"lead_log.csv: Dropped {na_dropped} (nulls), {duplicates_dropped} (duplicates).")

def clean_paid_transactions(input_file, output_file):
    """
    Cleans the paid_transactions.csv file by dropping nulls and duplicates,
    and standardizing the date format.
    """
    if not os.path.exists(input_file):
        raise AirflowException(f"Input file not found: {input_file}")

    df = pd.read_csv(input_file)
    initial_rows = len(df)
    df.dropna(subset=['transaction_id', 'transaction_at'], inplace=True)
    rows_after_na = len(df)
    df.drop_duplicates(inplace=True)
    rows_after_duplicates = len(df)
    df['transaction_at'] = pd.to_datetime(df['transaction_at'], utc=True)
    df.to_csv(output_file, index=False)

    na_dropped = initial_rows - rows_after_na
    duplicates_dropped = rows_after_na - rows_after_duplicates
    print(f"paid_transactions.csv: Dropped {na_dropped} (nulls), {duplicates_dropped} (duplicates).")

def clean_referral_rewards(input_file, output_file):
    """
    Cleans the referral_rewards.csv file by dropping nulls and duplicates,
    and standardizing the date format.
    """
    if not os.path.exists(input_file):
        raise AirflowException(f"Input file not found: {input_file}")

    df = pd.read_csv(input_file)
    initial_rows = len(df)
    df.dropna(subset=['id', 'created_at'], inplace=True)
    rows_after_na = len(df)
    df.drop_duplicates(inplace=True)
    rows_after_duplicates = len(df)
    df['created_at'] = pd.to_datetime(df['created_at'], utc=True)
    df.to_csv(output_file, index=False)

    na_dropped = initial_rows - rows_after_na
    duplicates_dropped = rows_after_na - rows_after_duplicates
    print(f"referral_rewards.csv: Dropped {na_dropped} (nulls), {duplicates_dropped} (duplicates).")

def clean_user_logs(input_file, output_file):
    """
    Cleans the user_logs.csv file by dropping nulls and duplicates,
    and standardizing the date format.
    """
    if not os.path.exists(input_file):
        raise AirflowException(f"Input file not found: {input_file}")

    df = pd.read_csv(input_file)
    initial_rows = len(df)
    df.dropna(subset=['id', 'user_id', 'membership_expired_date'], inplace=True)
    rows_after_na = len(df)
    df.drop_duplicates(inplace=True)
    rows_after_duplicates = len(df)
    df['membership_expired_date'] = pd.to_datetime(df['membership_expired_date'], utc=True)
    df.to_csv(output_file, index=False)

    na_dropped = initial_rows - rows_after_na
    duplicates_dropped = rows_after_na - rows_after_duplicates
    print(f"user_logs.csv: Dropped {na_dropped} (nulls), {duplicates_dropped} (duplicates).")

def clean_user_referral_logs(input_file, output_file):
    """
    Cleans the user_referral_logs.csv file by dropping nulls and duplicates,
    and standardizing the date format.
    """
    if not os.path.exists(input_file):
        raise AirflowException(f"Input file not found: {input_file}")

    df = pd.read_csv(input_file)
    initial_rows = len(df)
    df.dropna(subset=['source_transaction_id', 'created_at'], inplace=True)
    rows_after_na = len(df)
    df.drop_duplicates(inplace=True)
    rows_after_duplicates = len(df)
    df['created_at'] = pd.to_datetime(df['created_at'], utc=True)
    df.to_csv(output_file, index=False)

    na_dropped = initial_rows - rows_after_na
    duplicates_dropped = rows_after_na - rows_after_duplicates
    print(f"user_referral_logs.csv: Dropped {na_dropped} (nulls), {duplicates_dropped} (duplicates).")

def clean_user_referral_statuses(input_file, output_file):
    """
    Cleans the user_referral_statuses.csv file by dropping nulls and duplicates,
    and standardizing the date format.
    """
    if not os.path.exists(input_file):
        raise AirflowException(f"Input file not found: {input_file}")

    df = pd.read_csv(input_file)
    initial_rows = len(df)
    df.dropna(subset=['id', 'created_at'], inplace=True)
    rows_after_na = len(df)
    df.drop_duplicates(inplace=True)
    rows_after_duplicates = len(df)
    df['created_at'] = pd.to_datetime(df['created_at'], utc=True)
    df.to_csv(output_file, index=False)

    na_dropped = initial_rows - rows_after_na
    duplicates_dropped = rows_after_na - rows_after_duplicates
    print(f"user_referral_statuses.csv: Dropped {na_dropped} (nulls), {duplicates_dropped} (duplicates).")

def clean_user_referrals(input_file, output_file):
    """
    Cleans the user_referrals.csv file by dropping nulls and duplicates,
    and standardizing date formats.
    """
    if not os.path.exists(input_file):
        raise AirflowException(f"Input file not found: {input_file}")

    df = pd.read_csv(input_file)
    initial_rows = len(df)
    required_fields = [
        'referral_at', 'referral_id', 'referee_id', 'referral_reward_id',
        'referrer_id', 'transaction_id', 'updated_at', 'user_referral_status_id'
    ]
    df.dropna(subset=required_fields, inplace=True)
    rows_after_na = len(df)
    df.drop_duplicates(inplace=True)
    rows_after_duplicates = len(df)
    df['referral_at'] = pd.to_datetime(df['referral_at'], utc=True)
    df['updated_at'] = pd.to_datetime(df['updated_at'], utc=True)
    df.to_csv(output_file, index=False)

    na_dropped = initial_rows - rows_after_na
    duplicates_dropped = rows_after_na - rows_after_duplicates
    print(f"user_referrals.csv: Dropped {na_dropped} (nulls), {duplicates_dropped} (duplicates).")

# A dispatch table that maps file names to their corresponding cleaning function.
CLEANING_FUNCTIONS = {
    'lead_log.csv': clean_lead_log,
    'paid_transactions.csv': clean_paid_transactions,
    'referral_rewards.csv': clean_referral_rewards,
    'user_logs.csv': clean_user_logs,
    'user_referral_logs.csv': clean_user_referral_logs,
    'user_referral_statuses.csv': clean_user_referral_statuses,
    'user_referrals.csv': clean_user_referrals,
}

# This block defines the DAG, its properties, and the tasks within it.
with DAG(
    dag_id='cleansing_and_transformation_dag',
    start_date=datetime(2025, 1, 1),
    schedule=None,
    catchup=False,
    tags=['transformation', 'cleansing', 'staging'],
) as dag:

    # This list will hold all the cleaning task objects for dependency setting.
    cleaning_tasks = []
    # This loop dynamically generates one cleaning task for each file.
    for file in CSV_FILES:
        task = PythonOperator(
            task_id=f'clean_{file.replace(".csv", "")}',
            python_callable=CLEANING_FUNCTIONS[file],
            op_kwargs={
                'input_file': os.path.join(RAW_DATA_PATH, file),
                'output_file': os.path.join(CLEANED_DATA_PATH, file.replace('.csv', '_cleaned.csv')),
            }
        )
        cleaning_tasks.append(task)

    # This task triggers the downstream validation and publish DAG.
    trigger_downstream_dag = TriggerDagRunOperator(
        task_id='trigger_output_validation_dag',
        trigger_dag_id='output_validation_and_publish_dag_to_deltalake',
        # Passes the logical date to the triggered DAG for consistency.
        conf={"logical_date": "{{ ds }}"},
    )

    # This sets the dependency, ensuring the trigger runs only after all cleaning tasks succeed.
    cleaning_tasks >> trigger_downstream_dag