-- Redtail Portfolio Data Processing
-- Source: Read from Kafka with ARRAY<ROW> schema

CREATE TABLE redtail_portfolio_raw_input (
    scan_id STRING,
    entity_type STRING,
    glynac_organization_id STRING,
    batch_offset BIGINT,
    batch_size INT,
    batch_number INT,
    `timestamp` STRING,
    status STRING,
    message_type STRING,
    records ARRAY<ROW(
        rec_id INT,
        portfolio_name STRING,
        portfolio_code STRING,
        portfolio_type STRING,
        strategy STRING,
        objective STRING,
        risk_level STRING,
        target_return STRING,
        ytd_return STRING,
        one_year_return STRING,
        three_year_return STRING,
        five_year_return STRING,
        inception_return STRING,
        created_by INT,
        manager_id INT,
        inception_date STRING,
        description STRING,
        is_model BOOLEAN,
        is_active BOOLEAN,
        rec_add STRING,
        rec_add_user INT,
        rec_edit STRING,
        rec_edit_user INT,
        id INT,
        notes STRING,
        accounts_data STRING,
        portfolio_allocations_data STRING
    )>,
    processing_time AS PROCTIME()
) WITH (
    'connector' = 'kafka',
    'topic' = 'redtail-portfolios-stream',
    'properties.bootstrap.servers' = '{{KAFKA_BOOTSTRAP_SERVERS}}',,
    'properties.group.id' = 'redtail-portfolio-orc-processor',
    'scan.startup.mode' = 'earliest-offset',
    'format' = 'json',
    'json.fail-on-missing-field' = 'false',
    'json.ignore-parse-errors' = 'true'
);

-- Sink: Write to MinIO as ORC
CREATE TABLE redtail_portfolio_storage (
    scan_id STRING,
    glynac_organization_id STRING,
    entity_type STRING,
    batch_offset BIGINT,
    batch_size INT,
    batch_number INT,
    batch_timestamp STRING,
    status STRING,
    message_type STRING,
    rec_id INT,
    portfolio_id INT,
    portfolio_name STRING,
    portfolio_code STRING,
    portfolio_type STRING,
    strategy STRING,
    objective STRING,
    risk_level STRING,
    target_return STRING,
    ytd_return STRING,
    one_year_return STRING,
    three_year_return STRING,
    five_year_return STRING,
    inception_return STRING,
    created_by INT,
    manager_id INT,
    inception_date STRING,
    description STRING,
    is_model BOOLEAN,
    is_active BOOLEAN,
    rec_add STRING,
    rec_add_user INT,
    rec_edit STRING,
    rec_edit_user INT,
    notes STRING,
    accounts_data STRING,
    portfolio_allocations_data STRING,
    processing_timestamp STRING,
    processing_date STRING
) PARTITIONED BY (glynac_organization_id, processing_date)
WITH (
    'connector' = 'filesystem',
    'path' = 's3a://main-data/redtail/portfolio/',
    'format' = 'orc',
    'sink.rolling-policy.rollover-interval' = '1day',
    'sink.rolling-policy.check-interval' = '1h'
);

-- UNNEST and write
INSERT INTO redtail_portfolio_storage
SELECT 
    COALESCE(scan_id, 'UNKNOWN') as scan_id,
    COALESCE(glynac_organization_id, 'unknown') as glynac_organization_id,
    COALESCE(entity_type, 'portfolio') as entity_type,
    COALESCE(batch_offset, 0) as batch_offset,
    COALESCE(batch_size, 0) as batch_size,
    COALESCE(batch_number, 0) as batch_number,
    COALESCE(`timestamp`, CAST(CURRENT_TIMESTAMP AS STRING)) as batch_timestamp,
    COALESCE(status, 'unknown') as status,
    COALESCE(message_type, 'batch_data') as message_type,
    COALESCE(portfolio.rec_id, 0) as rec_id,
    COALESCE(portfolio.id, 0) as portfolio_id,
    COALESCE(portfolio.portfolio_name, '') as portfolio_name,
    COALESCE(portfolio.portfolio_code, '') as portfolio_code,
    COALESCE(portfolio.portfolio_type, '') as portfolio_type,
    COALESCE(portfolio.strategy, '') as strategy,
    COALESCE(portfolio.objective, '') as objective,
    COALESCE(portfolio.risk_level, '') as risk_level,
    COALESCE(portfolio.target_return, '0') as target_return,
    COALESCE(portfolio.ytd_return, '0') as ytd_return,
    COALESCE(portfolio.one_year_return, '0') as one_year_return,
    COALESCE(portfolio.three_year_return, '0') as three_year_return,
    COALESCE(portfolio.five_year_return, '0') as five_year_return,
    COALESCE(portfolio.inception_return, '0') as inception_return,
    COALESCE(portfolio.created_by, 0) as created_by,
    COALESCE(portfolio.manager_id, 0) as manager_id,
    COALESCE(portfolio.inception_date, '') as inception_date,
    COALESCE(portfolio.description, '') as description,
    COALESCE(portfolio.is_model, false) as is_model,
    COALESCE(portfolio.is_active, true) as is_active,
    COALESCE(portfolio.rec_add, '') as rec_add,
    COALESCE(portfolio.rec_add_user, 0) as rec_add_user,
    COALESCE(portfolio.rec_edit, '') as rec_edit,
    COALESCE(portfolio.rec_edit_user, 0) as rec_edit_user,
    COALESCE(portfolio.notes, '') as notes,
    COALESCE(portfolio.accounts_data, '') as accounts_data,
    COALESCE(portfolio.portfolio_allocations_data, '') as portfolio_allocations_data,
    CAST(processing_time AS STRING) as processing_timestamp,
    DATE_FORMAT(processing_time, 'yyyy-MM-dd') as processing_date
FROM redtail_portfolio_raw_input
CROSS JOIN UNNEST(records) AS portfolio;
