-- Redtail Asset Data Processing
-- Source: Read from Kafka with ARRAY<ROW> schema

CREATE TABLE redtail_asset_raw_input (
    scan_id STRING,
    entity_type STRING,
    glynac_organization_id STRING,
    batch_offset BIGINT,
    batch_size INT,
    batch_number INT,
    `timestamp` STRING,
    status STRING,
    message_type STRING,
    records ARRAY<ROW(
        rec_id BIGINT,
        account_id BIGINT,
        investment_id BIGINT,
        quantity STRING,
        cost_basis STRING,
        cost_basis_per_unit STRING,
        current_price STRING,
        current_value STRING,
        unrealized_gain_loss STRING,
        unrealized_gain_loss_percent STRING,
        allocation_percent STRING,
        target_allocation STRING,
        purchase_date STRING,
        last_update_date STRING,
        is_core_position BOOLEAN,
        is_active BOOLEAN,
        rec_add STRING,
        rec_add_user BIGINT,
        rec_edit STRING,
        rec_edit_user BIGINT,
        investment_data STRING,
        id BIGINT,
        notes STRING
    )>,
    processing_time AS PROCTIME()
) WITH (
    'connector' = 'kafka',
    'topic' = 'redtail-assets-stream',
    'properties.bootstrap.servers' = '{{KAFKA_BOOTSTRAP_SERVERS}}',,
    'properties.group.id' = 'redtail-asset-orc-processor',
    'scan.startup.mode' = 'earliest-offset',
    'format' = 'json',
    'json.fail-on-missing-field' = 'false',
    'json.ignore-parse-errors' = 'true'
);

-- Sink: Write to MinIO as ORC
CREATE TABLE redtail_asset_storage (
    scan_id STRING,
    glynac_organization_id STRING,
    entity_type STRING,
    batch_timestamp STRING,
    batch_number INT,
    batch_offset BIGINT,
    message_type STRING,
    status STRING,
    rec_id BIGINT,
    account_id BIGINT,
    investment_id BIGINT,
    asset_id BIGINT,
    quantity STRING,
    cost_basis STRING,
    cost_basis_per_unit STRING,
    current_price STRING,
    current_value STRING,
    unrealized_gain_loss STRING,
    unrealized_gain_loss_percent STRING,
    allocation_percent STRING,
    target_allocation STRING,
    purchase_date STRING,
    last_update_date STRING,
    is_core_position BOOLEAN,
    is_active BOOLEAN,
    rec_add STRING,
    rec_add_user BIGINT,
    rec_edit STRING,
    rec_edit_user BIGINT,
    investment_data STRING,
    notes STRING,
    processing_timestamp STRING,
    processing_date STRING
) PARTITIONED BY (glynac_organization_id, processing_date)
WITH (
    'connector' = 'filesystem',
    'path' = 's3a://main-data/redtail/asset/',
    'format' = 'orc',
    'sink.rolling-policy.rollover-interval' = '1day',
    'sink.rolling-policy.check-interval' = '1h'
);

-- UNNEST and write
INSERT INTO redtail_asset_storage
SELECT 
    COALESCE(scan_id, 'UNKNOWN') as scan_id,
    COALESCE(glynac_organization_id, 'unknown') as glynac_organization_id,
    COALESCE(entity_type, 'asset') as entity_type,
    COALESCE(`timestamp`, CAST(CURRENT_TIMESTAMP AS STRING)) as batch_timestamp,
    COALESCE(batch_number, 0) as batch_number,
    COALESCE(batch_offset, 0) as batch_offset,
    COALESCE(message_type, 'batch_data') as message_type,
    COALESCE(status, 'unknown') as status,
    COALESCE(asset.rec_id, 0) as rec_id,
    COALESCE(asset.account_id, 0) as account_id,
    COALESCE(asset.investment_id, 0) as investment_id,
    COALESCE(asset.id, 0) as asset_id,
    COALESCE(asset.quantity, '0') as quantity,
    COALESCE(asset.cost_basis, '0') as cost_basis,
    COALESCE(asset.cost_basis_per_unit, '0') as cost_basis_per_unit,
    COALESCE(asset.current_price, '0') as current_price,
    COALESCE(asset.current_value, '0') as current_value,
    COALESCE(asset.unrealized_gain_loss, '0') as unrealized_gain_loss,
    COALESCE(asset.unrealized_gain_loss_percent, '0') as unrealized_gain_loss_percent,
    COALESCE(asset.allocation_percent, '0') as allocation_percent,
    COALESCE(asset.target_allocation, '0') as target_allocation,
    COALESCE(asset.purchase_date, '') as purchase_date,
    COALESCE(asset.last_update_date, '') as last_update_date,
    COALESCE(asset.is_core_position, false) as is_core_position,
    COALESCE(asset.is_active, true) as is_active,
    COALESCE(asset.rec_add, '') as rec_add,
    COALESCE(asset.rec_add_user, 0) as rec_add_user,
    COALESCE(asset.rec_edit, '') as rec_edit,
    COALESCE(asset.rec_edit_user, 0) as rec_edit_user,
    COALESCE(asset.investment_data, '{}') as investment_data,
    COALESCE(asset.notes, '') as notes,
    CAST(processing_time AS STRING) as processing_timestamp,
    DATE_FORMAT(processing_time, 'yyyy-MM-dd') as processing_date
FROM redtail_asset_raw_input
CROSS JOIN UNNEST(records) AS asset;
