-- Redtail Transaction Data Processing
-- Source: Read from Kafka with ARRAY<ROW> schema

CREATE TABLE redtail_transaction_raw_input (
    scan_id STRING,
    entity_type STRING,
    glynac_organization_id STRING,
    batch_offset BIGINT,
    batch_size INT,
    batch_number INT,
    `timestamp` STRING,
    status STRING,
    message_type STRING,
    records ARRAY<ROW(
        rec_id INT,
        transaction_number STRING,
        transaction_type STRING,
        account_id INT,
        investment_id INT,
        amount STRING,
        fees STRING,
        currency STRING,
        transaction_date STRING,
        settlement_date STRING,
        entry_date STRING,
        status STRING,
        description STRING,
        notes STRING,
        reference_number STRING,
        is_active BOOLEAN,
        rec_add STRING,
        rec_add_user INT,
        rec_edit STRING,
        rec_edit_user INT,
        investment STRING,
        id INT,
        investment_data STRING,
        price_per_unit STRING,
        quantity STRING
    )>,
    processing_time AS PROCTIME()
) WITH (
    'connector' = 'kafka',
    'topic' = 'redtail-transactions-stream',
    'properties.bootstrap.servers' = '{{KAFKA_BOOTSTRAP_SERVERS}}',,
    'properties.group.id' = 'redtail-transaction-orc-processor',
    'scan.startup.mode' = 'earliest-offset',
    'format' = 'json',
    'json.fail-on-missing-field' = 'false',
    'json.ignore-parse-errors' = 'true'
);

-- Sink: Write to MinIO as ORC
CREATE TABLE redtail_transaction_storage (
    scan_id STRING,
    glynac_organization_id STRING,
    entity_type STRING,
    batch_timestamp STRING,
    batch_number INT,
    batch_offset BIGINT,
    message_type STRING,
    rec_id INT,
    transaction_id INT,
    transaction_number STRING,
    transaction_type STRING,
    account_id INT,
    investment_id INT,
    amount STRING,
    fees STRING,
    currency STRING,
    transaction_date STRING,
    settlement_date STRING,
    entry_date STRING,
    transaction_status STRING,
    description STRING,
    notes STRING,
    reference_number STRING,
    is_active BOOLEAN,
    investment STRING,
    investment_data STRING,
    price_per_unit STRING,
    quantity STRING,
    rec_add STRING,
    rec_add_user INT,
    rec_edit STRING,
    rec_edit_user INT,
    processing_timestamp STRING,
    processing_date STRING
) PARTITIONED BY (glynac_organization_id, processing_date)
WITH (
    'connector' = 'filesystem',
    'path' = 's3a://main-data/redtail/transaction/',
    'format' = 'orc',
    'sink.rolling-policy.rollover-interval' = '1day',
    'sink.rolling-policy.check-interval' = '1h'
);

-- UNNEST and write
INSERT INTO redtail_transaction_storage
SELECT 
    COALESCE(scan_id, 'UNKNOWN') as scan_id,
    COALESCE(glynac_organization_id, 'unknown') as glynac_organization_id,
    COALESCE(entity_type, 'transaction') as entity_type,
    COALESCE(`timestamp`, CAST(CURRENT_TIMESTAMP AS STRING)) as batch_timestamp,
    COALESCE(batch_number, 0) as batch_number,
    COALESCE(batch_offset, 0) as batch_offset,
    COALESCE(message_type, '') as message_type,
    COALESCE(txn.rec_id, 0) as rec_id,
    COALESCE(txn.id, 0) as transaction_id,
    COALESCE(txn.transaction_number, '') as transaction_number,
    COALESCE(txn.transaction_type, '') as transaction_type,
    COALESCE(txn.account_id, 0) as account_id,
    COALESCE(txn.investment_id, 0) as investment_id,
    COALESCE(txn.amount, '0') as amount,
    COALESCE(txn.fees, '0') as fees,
    COALESCE(txn.currency, 'USD') as currency,
    COALESCE(txn.transaction_date, '') as transaction_date,
    COALESCE(txn.settlement_date, '') as settlement_date,
    COALESCE(txn.entry_date, '') as entry_date,
    COALESCE(txn.status, 'Unknown') as transaction_status,
    COALESCE(txn.description, '') as description,
    COALESCE(txn.notes, '') as notes,
    COALESCE(txn.reference_number, '') as reference_number,
    COALESCE(txn.is_active, true) as is_active,
    COALESCE(txn.investment, '') as investment,
    COALESCE(txn.investment_data, '') as investment_data,
    COALESCE(txn.price_per_unit, '') as price_per_unit,
    COALESCE(txn.quantity, '') as quantity,
    COALESCE(txn.rec_add, '') as rec_add,
    COALESCE(txn.rec_add_user, 0) as rec_add_user,
    COALESCE(txn.rec_edit, '') as rec_edit,
    COALESCE(txn.rec_edit_user, 0) as rec_edit_user,
    CAST(processing_time AS STRING) as processing_timestamp,
    DATE_FORMAT(processing_time, 'yyyy-MM-dd') as processing_date
FROM redtail_transaction_raw_input
CROSS JOIN UNNEST(records) AS txn;
