-- Redtail Net Worth Data Processing
-- Source: Read from Kafka with ARRAY<ROW> schema

CREATE TABLE redtail_net_worth_raw_input (
    scan_id STRING,
    entity_type STRING,
    glynac_organization_id STRING,
    batch_offset INT,
    batch_size INT,
    batch_number INT,
    `timestamp` STRING,
    status STRING,
    message_type STRING,
    records ARRAY<ROW(
        rec_id INT,
        contact_id INT,
        as_of_date STRING,
        cash_and_equivalents STRING,
        investments STRING,
        retirement_accounts STRING,
        real_estate STRING,
        business_interests STRING,
        personal_property STRING,
        other_assets STRING,
        total_assets STRING,
        short_term_liabilities STRING,
        mortgages STRING,
        loans STRING,
        other_liabilities STRING,
        total_liabilities STRING,
        net_worth_amount STRING,
        rec_add STRING,
        rec_add_user INT,
        rec_edit STRING,
        rec_edit_user INT,
        id INT,
        notes STRING
    )>,
    processing_time AS PROCTIME()
) WITH (
    'connector' = 'kafka',
    'topic' = 'redtail-net_worth-stream',
    'properties.bootstrap.servers' = '{{KAFKA_BOOTSTRAP_SERVERS}}',,
    'properties.group.id' = 'redtail-net-worth-orc-processor',
    'scan.startup.mode' = 'earliest-offset',
    'format' = 'json',
    'json.fail-on-missing-field' = 'false',
    'json.ignore-parse-errors' = 'true'
);

-- Sink: Write to MinIO as ORC
CREATE TABLE redtail_net_worth_storage (
    scan_id STRING,
    glynac_organization_id STRING,
    entity_type STRING,
    batch_timestamp STRING,
    batch_number INT,
    batch_offset INT,
    status STRING,
    message_type STRING,
    rec_id INT,
    contact_id INT,
    as_of_date STRING,
    cash_and_equivalents STRING,
    investments STRING,
    retirement_accounts STRING,
    real_estate STRING,
    business_interests STRING,
    personal_property STRING,
    other_assets STRING,
    total_assets STRING,
    short_term_liabilities STRING,
    mortgages STRING,
    loans STRING,
    other_liabilities STRING,
    total_liabilities STRING,
    net_worth_amount STRING,
    rec_add STRING,
    rec_add_user INT,
    rec_edit STRING,
    rec_edit_user INT,
    record_id INT,
    notes STRING,
    processing_timestamp STRING,
    processing_date STRING
) PARTITIONED BY (glynac_organization_id, processing_date)
WITH (
    'connector' = 'filesystem',
    'path' = 's3a://main-data/redtail/net_worth/',
    'format' = 'orc',
    'sink.rolling-policy.rollover-interval' = '1day',
    'sink.rolling-policy.check-interval' = '1h'
);

-- UNNEST and write
INSERT INTO redtail_net_worth_storage
SELECT 
    COALESCE(scan_id, 'UNKNOWN') as scan_id,
    COALESCE(glynac_organization_id, 'unknown') as glynac_organization_id,
    COALESCE(entity_type, 'net_worth') as entity_type,
    COALESCE(`timestamp`, CAST(CURRENT_TIMESTAMP AS STRING)) as batch_timestamp,
    COALESCE(batch_number, 0) as batch_number,
    COALESCE(batch_offset, 0) as batch_offset,
    COALESCE(status, 'unknown') as status,
    COALESCE(message_type, 'batch_data') as message_type,
    COALESCE(record.rec_id, 0) as rec_id,
    COALESCE(record.contact_id, 0) as contact_id,
    COALESCE(record.as_of_date, '') as as_of_date,
    COALESCE(record.cash_and_equivalents, '0.00') as cash_and_equivalents,
    COALESCE(record.investments, '0.00') as investments,
    COALESCE(record.retirement_accounts, '0.00') as retirement_accounts,
    COALESCE(record.real_estate, '0.00') as real_estate,
    COALESCE(record.business_interests, '0.00') as business_interests,
    COALESCE(record.personal_property, '0.00') as personal_property,
    COALESCE(record.other_assets, '0.00') as other_assets,
    COALESCE(record.total_assets, '0.00') as total_assets,
    COALESCE(record.short_term_liabilities, '0.00') as short_term_liabilities,
    COALESCE(record.mortgages, '0.00') as mortgages,
    COALESCE(record.loans, '0.00') as loans,
    COALESCE(record.other_liabilities, '0.00') as other_liabilities,
    COALESCE(record.total_liabilities, '0.00') as total_liabilities,
    COALESCE(record.net_worth_amount, '0.00') as net_worth_amount,
    COALESCE(record.rec_add, '') as rec_add,
    COALESCE(record.rec_add_user, 0) as rec_add_user,
    COALESCE(record.rec_edit, '') as rec_edit,
    COALESCE(record.rec_edit_user, 0) as rec_edit_user,
    COALESCE(record.id, 0) as record_id,
    COALESCE(record.notes, '') as notes,
    CAST(processing_time AS STRING) as processing_timestamp,
    DATE_FORMAT(processing_time, 'yyyy-MM-dd') as processing_date
FROM redtail_net_worth_raw_input
CROSS JOIN UNNEST(records) AS record;
