dataset_name: "phoebe_user_ingestion"
table_name: "stg_phoebe_users"
description: "Ingesting user mock data from SharePoint CSV"
columns:
  - name: "id"
    type: "INTEGER"
  - name: "first_name"
    type: "VARCHAR(100)"
  - name: "last_name"
    type: "VARCHAR(100)"
  - name: "email"
    type: "VARCHAR(255)"
  - name: "gender"
    type: "VARCHAR(20)"
  - name: "ip_address"
    type: "VARCHAR(50)"