-- Salesforce Campaign Data Processing
-- Source: Read from Kafka with ARRAY<ROW> schema

CREATE TABLE salesforce_campaign_raw_input (
    scan_id STRING,
    service STRING,
    `timestamp` STRING,
    `offset` BIGINT,
    page INT,
    page_size INT,
    batch_size INT,
    total_streamed INT,
    total_data_streamed INT,
    total_available INT,
    table_name STRING,
    columns ARRAY<STRING>,
    available_tables ARRAY<STRING>,
    glynac_organization_id STRING,
    data ARRAY<ROW(
        attributes__type STRING,
        attributes__url STRING,
        id STRING,
        name STRING,
        type STRING,
        status STRING,
        start_date STRING,
        end_date STRING,
        is_active BOOLEAN,
        budgeted_cost DOUBLE,
        actual_cost DOUBLE,
        expected_revenue DOUBLE,
        expected_response DOUBLE,
        number_sent DOUBLE,
        number_of_leads INT,
        number_of_converted_leads INT,
        number_of_contacts INT,
        number_of_responses INT,
        number_of_opportunities INT,
        number_of_won_opportunities INT,
        amount_all_opportunities DOUBLE,
        amount_won_opportunities DOUBLE,
        created_date STRING,
        last_modified_date STRING,
        owner_id STRING,
        owner__attributes__type STRING,
        owner__attributes__url STRING,
        owner__name STRING,
        owner__email STRING,
        _extracted_at STRING,
        _scan_id STRING,
        _organization_id STRING,
        _page_number INT,
        _source_service STRING,
        _token_refresh_supported BOOLEAN,
        _dlt_load_id STRING,
        _dlt_id STRING
    )>,
    processing_time AS PROCTIME()
) WITH (
    'connector' = 'kafka',
    'topic' = 'sf-stream-campaigns',
    'properties.bootstrap.servers' = '{{KAFKA_BOOTSTRAP_SERVERS}}',
    'properties.group.id' = 'salesforce-campaign-orc-processor',
    'scan.startup.mode' = 'earliest-offset',
    'format' = 'json',
    'json.fail-on-missing-field' = 'false',
    'json.ignore-parse-errors' = 'true'
);

-- Sink: Write to MinIO as ORC
CREATE TABLE salesforce_campaign_storage (
    scan_id STRING,
    glynac_organization_id STRING,
    service STRING,
    batch_timestamp STRING,
    page_number INT,
    table_name STRING,
    campaign_id STRING,
    campaign_name STRING,
    campaign_type STRING,
    campaign_status STRING,
    start_date STRING,
    end_date STRING,
    is_active BOOLEAN,
    budgeted_cost DOUBLE,
    actual_cost DOUBLE,
    expected_revenue DOUBLE,
    expected_response DOUBLE,
    number_sent DOUBLE,
    number_of_leads INT,
    number_of_converted_leads INT,
    number_of_contacts INT,
    number_of_responses INT,
    number_of_opportunities INT,
    number_of_won_opportunities INT,
    amount_all_opportunities DOUBLE,
    amount_won_opportunities DOUBLE,
    owner_id STRING,
    owner_name STRING,
    owner_email STRING,
    created_date STRING,
    last_modified_date STRING,
    extracted_at STRING,
    source_service STRING,
    processing_timestamp STRING,
    processing_date STRING
) PARTITIONED BY (glynac_organization_id, processing_date)
WITH (
    'connector' = 'filesystem',
    'path' = '{{MINIO_S3_ENDPOINT}}/salesforce/campaign/',
    'format' = 'orc',
    'sink.rolling-policy.rollover-interval' = '1day',
    'sink.rolling-policy.check-interval' = '1h'
);

-- UNNEST and write
INSERT INTO salesforce_campaign_storage
SELECT 
    COALESCE(scan_id, 'UNKNOWN') as scan_id,
    COALESCE(glynac_organization_id, 'unknown') as glynac_organization_id,
    COALESCE(service, 'salesforce_campaign') as service,
    COALESCE(`timestamp`, CAST(CURRENT_TIMESTAMP AS STRING)) as batch_timestamp,
    COALESCE(page, 0) as page_number,
    COALESCE(table_name, 'salesforce_campaigns') as table_name,
    COALESCE(campaign.id, 'NONE') as campaign_id,
    COALESCE(campaign.name, 'No Name') as campaign_name,
    COALESCE(campaign.type, 'Unknown') as campaign_type,
    COALESCE(campaign.status, 'Unknown') as campaign_status,
    COALESCE(campaign.start_date, '') as start_date,
    COALESCE(campaign.end_date, '') as end_date,
    COALESCE(campaign.is_active, false) as is_active,
    COALESCE(campaign.budgeted_cost, 0.0) as budgeted_cost,
    COALESCE(campaign.actual_cost, 0.0) as actual_cost,
    COALESCE(campaign.expected_revenue, 0.0) as expected_revenue,
    COALESCE(campaign.expected_response, 0.0) as expected_response,
    COALESCE(campaign.number_sent, 0.0) as number_sent,
    COALESCE(campaign.number_of_leads, 0) as number_of_leads,
    COALESCE(campaign.number_of_converted_leads, 0) as number_of_converted_leads,
    COALESCE(campaign.number_of_contacts, 0) as number_of_contacts,
    COALESCE(campaign.number_of_responses, 0) as number_of_responses,
    COALESCE(campaign.number_of_opportunities, 0) as number_of_opportunities,
    COALESCE(campaign.number_of_won_opportunities, 0) as number_of_won_opportunities,
    COALESCE(campaign.amount_all_opportunities, 0.0) as amount_all_opportunities,
    COALESCE(campaign.amount_won_opportunities, 0.0) as amount_won_opportunities,
    COALESCE(campaign.owner_id, '') as owner_id,
    COALESCE(campaign.owner__name, '') as owner_name,
    COALESCE(campaign.owner__email, '') as owner_email,
    COALESCE(campaign.created_date, '') as created_date,
    COALESCE(campaign.last_modified_date, '') as last_modified_date,
    COALESCE(campaign._extracted_at, '') as extracted_at,
    COALESCE(campaign._source_service, 'salesforce') as source_service,
    CAST(processing_time AS STRING) as processing_timestamp,
    DATE_FORMAT(processing_time, 'yyyy-MM-dd') as processing_date
FROM salesforce_campaign_raw_input
CROSS JOIN UNNEST(data) AS campaign;