-- Redtail Account Data Processing
-- Source: Read from Kafka with ARRAY<ROW> schema

CREATE TABLE redtail_account_raw_input (
    scan_id STRING,
    entity_type STRING,
    glynac_organization_id STRING,
    batch_offset BIGINT,
    batch_size INT,
    batch_number INT,
    `timestamp` STRING,
    status STRING,
    message_type STRING,
    records ARRAY<ROW(
        rec_id INT,
        account_number STRING,
        account_name STRING,
        account_type STRING,
        account_status STRING,
        institution_name STRING,
        institution_type STRING,
        contact_id INT,
        portfolio_id INT,
        current_balance STRING,
        available_balance STRING,
        currency STRING,
        open_date STRING,
        tags STRING,
        is_active BOOLEAN,
        rec_add STRING,
        rec_add_user INT,
        rec_edit STRING,
        rec_edit_user INT,
        id INT,
        contact_data STRING,
        portfolio_data STRING,
        account_assets_data STRING,
        account_assets_count INT,
        description STRING
    )>,
    processing_time AS PROCTIME()
) WITH (
    'connector' = 'kafka',
    'topic' = 'redtail-account-stream',
    'properties.bootstrap.servers' = '{{KAFKA_BOOTSTRAP_SERVERS}}',
    'properties.group.id' = 'redtail-account-orc-processor',
    'scan.startup.mode' = 'earliest-offset',
    'format' = 'json',
    'json.fail-on-missing-field' = 'false',
    'json.ignore-parse-errors' = 'true'
);


-- Sink: Write to MinIO as ORC
CREATE TABLE redtail_account_storage (
    scan_id STRING,
    glynac_organization_id STRING,
    entity_type STRING,
    batch_timestamp STRING,
    batch_number INT,
    batch_offset BIGINT,
    status STRING,
    message_type STRING,
    rec_id INT,
    account_id INT,
    account_number STRING,
    account_name STRING,
    account_type STRING,
    account_status STRING,
    institution_name STRING,
    institution_type STRING,
    contact_id INT,
    portfolio_id INT,
    current_balance STRING,
    available_balance STRING,
    currency STRING,
    open_date STRING,
    tags STRING,
    is_active BOOLEAN,
    contact_data STRING,
    portfolio_data STRING,
    account_assets_data STRING,
    account_assets_count INT,
    description STRING,
    rec_add STRING,
    rec_add_user INT,
    rec_edit STRING,
    rec_edit_user INT,
    processing_timestamp STRING,
    processing_date STRING
) PARTITIONED BY (glynac_organization_id, processing_date)
WITH (
    'connector' = 'filesystem',
    'path' = '{{MINIO_S3_ENDPOINT}}/redtail/account/',
    'format' = 'orc',
    'sink.rolling-policy.rollover-interval' = '1day',
    'sink.rolling-policy.check-interval' = '1h'
);

-- UNNEST and write
INSERT INTO redtail_account_storage
SELECT 
    COALESCE(scan_id, 'UNKNOWN') as scan_id,
    COALESCE(glynac_organization_id, 'unknown') as glynac_organization_id,
    COALESCE(entity_type, 'account') as entity_type,
    COALESCE(`timestamp`, CAST(CURRENT_TIMESTAMP AS STRING)) as batch_timestamp,
    COALESCE(batch_number, 0) as batch_number,
    COALESCE(batch_offset, 0) as batch_offset,
    COALESCE(status, 'unknown') as status,
    COALESCE(message_type, 'batch_data') as message_type,
    COALESCE(account.rec_id, 0) as rec_id,
    COALESCE(account.id, 0) as account_id,
    COALESCE(account.account_number, '') as account_number,
    COALESCE(account.account_name, '') as account_name,
    COALESCE(account.account_type, '') as account_type,
    COALESCE(account.account_status, '') as account_status,
    COALESCE(account.institution_name, '') as institution_name,
    COALESCE(account.institution_type, '') as institution_type,
    COALESCE(account.contact_id, 0) as contact_id,
    COALESCE(account.portfolio_id, 0) as portfolio_id,
    COALESCE(account.current_balance, '0') as current_balance,
    COALESCE(account.available_balance, '0') as available_balance,
    COALESCE(account.currency, 'USD') as currency,
    COALESCE(account.open_date, '') as open_date,
    COALESCE(account.tags, '') as tags,
    COALESCE(account.is_active, false) as is_active,
    COALESCE(account.contact_data, '') as contact_data,
    COALESCE(account.portfolio_data, '') as portfolio_data,
    COALESCE(account.account_assets_data, '') as account_assets_data,
    COALESCE(account.account_assets_count, 0) as account_assets_count,
    COALESCE(account.description, '') as description,
    COALESCE(account.rec_add, '') as rec_add,
    COALESCE(account.rec_add_user, 0) as rec_add_user,
    COALESCE(account.rec_edit, '') as rec_edit,
    COALESCE(account.rec_edit_user, 0) as rec_edit_user,
    CAST(processing_time AS STRING) as processing_timestamp,
    DATE_FORMAT(processing_time, 'yyyy-MM-dd') as processing_date
FROM redtail_account_raw_input
CROSS JOIN UNNEST(records) AS account;
