-- Redtail Investment Data Processing
-- Source: Read from Kafka with ARRAY<ROW> schema

CREATE TABLE redtail_investment_raw_input (
    scan_id STRING,
    entity_type STRING,
    glynac_organization_id STRING,
    batch_offset BIGINT,
    batch_size INT,
    batch_number INT,
    `timestamp` STRING,
    status STRING,
    message_type STRING,
    records ARRAY<ROW(
        rec_id INT,
        investment_name STRING,
        symbol STRING,
        investment_type STRING,
        asset_class STRING,
        category STRING,
        current_price STRING,
        previous_close STRING,
        price_change STRING,
        price_change_percent STRING,
        description STRING,
        currency STRING,
        country STRING,
        coupon_rate STRING,
        maturity_date STRING,
        credit_rating STRING,
        ytd_return STRING,
        one_year_return STRING,
        three_year_return STRING,
        five_year_return STRING,
        dividend_yield STRING,
        is_active BOOLEAN,
        rec_add STRING,
        rec_add_user INT,
        rec_edit STRING,
        rec_edit_user INT,
        id INT,
        cusip STRING,
        isin STRING,
        expense_ratio STRING,
        fund_manager STRING,
        fund_family STRING,
        fund_aum STRING,
        exchange STRING,
        sector STRING,
        industry STRING
    )>,
    processing_time AS PROCTIME()
) WITH (
    'connector' = 'kafka',
    'topic' = 'redtail-investments-stream',
    'properties.bootstrap.servers' = '{{KAFKA_BOOTSTRAP_SERVERS}}',,
    'properties.group.id' = 'redtail-investment-orc-processor',
    'scan.startup.mode' = 'earliest-offset',
    'format' = 'json',
    'json.fail-on-missing-field' = 'false',
    'json.ignore-parse-errors' = 'true'
);

-- Sink: Write to MinIO as ORC
CREATE TABLE redtail_investment_storage (
    scan_id STRING,
    glynac_organization_id STRING,
    entity_type STRING,
    batch_number INT,
    batch_offset BIGINT,
    batch_timestamp STRING,
    message_type STRING,
    status STRING,
    rec_id INT,
    investment_id INT,
    investment_name STRING,
    symbol STRING,
    investment_type STRING,
    asset_class STRING,
    category STRING,
    current_price STRING,
    previous_close STRING,
    price_change STRING,
    price_change_percent STRING,
    description STRING,
    currency STRING,
    country STRING,
    coupon_rate STRING,
    maturity_date STRING,
    credit_rating STRING,
    ytd_return STRING,
    one_year_return STRING,
    three_year_return STRING,
    five_year_return STRING,
    dividend_yield STRING,
    is_active BOOLEAN,
    cusip STRING,
    isin STRING,
    expense_ratio STRING,
    fund_manager STRING,
    fund_family STRING,
    fund_aum STRING,
    exchange STRING,
    sector STRING,
    industry STRING,
    rec_add STRING,
    rec_add_user INT,
    rec_edit STRING,
    rec_edit_user INT,
    processing_timestamp STRING,
    processing_date STRING
) PARTITIONED BY (glynac_organization_id, processing_date)
WITH (
    'connector' = 'filesystem',
    'path' = 's3a://main-data/redtail/investment/',
    'format' = 'orc',
    'sink.rolling-policy.rollover-interval' = '1day',
    'sink.rolling-policy.check-interval' = '1h'
);

-- UNNEST and write
INSERT INTO redtail_investment_storage
SELECT 
    COALESCE(scan_id, 'UNKNOWN') as scan_id,
    COALESCE(glynac_organization_id, 'unknown') as glynac_organization_id,
    COALESCE(entity_type, 'investment') as entity_type,
    COALESCE(batch_number, 0) as batch_number,
    COALESCE(batch_offset, 0) as batch_offset,
    COALESCE(`timestamp`, CAST(CURRENT_TIMESTAMP AS STRING)) as batch_timestamp,
    COALESCE(message_type, 'batch_data') as message_type,
    COALESCE(status, 'unknown') as status,
    COALESCE(inv.rec_id, 0) as rec_id,
    COALESCE(inv.id, 0) as investment_id,
    COALESCE(inv.investment_name, '') as investment_name,
    COALESCE(inv.symbol, '') as symbol,
    COALESCE(inv.investment_type, '') as investment_type,
    COALESCE(inv.asset_class, '') as asset_class,
    COALESCE(inv.category, '') as category,
    COALESCE(inv.current_price, '0') as current_price,
    COALESCE(inv.previous_close, '0') as previous_close,
    COALESCE(inv.price_change, '0') as price_change,
    COALESCE(inv.price_change_percent, '0') as price_change_percent,
    COALESCE(inv.description, '') as description,
    COALESCE(inv.currency, 'USD') as currency,
    COALESCE(inv.country, 'USA') as country,
    COALESCE(inv.coupon_rate, '') as coupon_rate,
    COALESCE(inv.maturity_date, '') as maturity_date,
    COALESCE(inv.credit_rating, '') as credit_rating,
    COALESCE(inv.ytd_return, '') as ytd_return,
    COALESCE(inv.one_year_return, '') as one_year_return,
    COALESCE(inv.three_year_return, '') as three_year_return,
    COALESCE(inv.five_year_return, '') as five_year_return,
    COALESCE(inv.dividend_yield, '') as dividend_yield,
    COALESCE(inv.is_active, true) as is_active,
    COALESCE(inv.cusip, '') as cusip,
    COALESCE(inv.isin, '') as isin,
    COALESCE(inv.expense_ratio, '') as expense_ratio,
    COALESCE(inv.fund_manager, '') as fund_manager,
    COALESCE(inv.fund_family, '') as fund_family,
    COALESCE(inv.fund_aum, '') as fund_aum,
    COALESCE(inv.exchange, '') as exchange,
    COALESCE(inv.sector, '') as sector,
    COALESCE(inv.industry, '') as industry,
    COALESCE(inv.rec_add, '') as rec_add,
    COALESCE(inv.rec_add_user, 0) as rec_add_user,
    COALESCE(inv.rec_edit, '') as rec_edit,
    COALESCE(inv.rec_edit_user, 0) as rec_edit_user,
    CAST(processing_time AS STRING) as processing_timestamp,
    DATE_FORMAT(processing_time, 'yyyy-MM-dd') as processing_date
FROM redtail_investment_raw_input
CROSS JOIN UNNEST(records) AS inv;
