-- Redtail Contact Data Processing
-- Source: Read from Kafka with ARRAY<ROW> schema

CREATE TABLE redtail_contact_raw_input (
    scan_id STRING,
    entity_type STRING,
    glynac_organization_id STRING,
    batch_offset BIGINT,
    batch_size INT,
    batch_number INT,
    `timestamp` STRING,
    status STRING,
    message_type STRING,
    records ARRAY<ROW(
        first_name STRING,
        last_name STRING,
        full_name STRING,
        prefix STRING,
        email STRING,
        phone_number STRING,
        phone_number2 STRING,
        mobile_phone STRING,
        work_phone STRING,
        home_phone STRING,
        address1 STRING,
        city STRING,
        state STRING,
        zip_code STRING,
        country STRING,
        date_of_birth STRING,
        gender STRING,
        marital_status STRING,
        occupation STRING,
        company_name STRING,
        job_title STRING,
        contact_type STRING,
        status STRING,
        assigned_to INT,
        rec_id INT,
        rec_add STRING,
        rec_edit STRING,
        id INT,
        fax_number STRING
    )>,
    processing_time AS PROCTIME()
) WITH (
    'connector' = 'kafka',
    'topic' = 'redtail-contacts-stream',
    'properties.bootstrap.servers' = '{{KAFKA_BOOTSTRAP_SERVERS}}',
    'properties.group.id' = 'redtail-contact-orc-processor',
    'scan.startup.mode' = 'earliest-offset',
    'format' = 'json',
    'json.fail-on-missing-field' = 'false',
    'json.ignore-parse-errors' = 'true'
);

-- Sink: Write to MinIO as ORC
CREATE TABLE redtail_contact_storage (
    scan_id STRING,
    glynac_organization_id STRING,
    entity_type STRING,
    batch_timestamp STRING,
    batch_number INT,
    batch_offset BIGINT,
    message_type STRING,
    contact_id INT,
    rec_id INT,
    first_name STRING,
    last_name STRING,
    full_name STRING,
    prefix STRING,
    email STRING,
    phone_number STRING,
    phone_number2 STRING,
    mobile_phone STRING,
    work_phone STRING,
    home_phone STRING,
    fax_number STRING,
    address1 STRING,
    city STRING,
    state STRING,
    zip_code STRING,
    country STRING,
    date_of_birth STRING,
    gender STRING,
    marital_status STRING,
    occupation STRING,
    company_name STRING,
    job_title STRING,
    contact_type STRING,
    contact_status STRING,
    assigned_to INT,
    rec_add STRING,
    rec_edit STRING,
    processing_timestamp STRING,
    processing_date STRING
) PARTITIONED BY (glynac_organization_id, processing_date)
WITH (
    'connector' = 'filesystem',
    'path' = 's3a://main-data/redtail/contact/',
    'format' = 'orc',
    'sink.rolling-policy.rollover-interval' = '1day',
    'sink.rolling-policy.check-interval' = '1h'
);

-- UNNEST and write
INSERT INTO redtail_contact_storage
SELECT 
    COALESCE(scan_id, 'UNKNOWN') as scan_id,
    COALESCE(glynac_organization_id, 'unknown') as glynac_organization_id,
    COALESCE(entity_type, 'contact') as entity_type,
    COALESCE(`timestamp`, CAST(CURRENT_TIMESTAMP AS STRING)) as batch_timestamp,
    COALESCE(batch_number, 0) as batch_number,
    COALESCE(batch_offset, 0) as batch_offset,
    COALESCE(message_type, 'batch_data') as message_type,
    COALESCE(contact.id, 0) as contact_id,
    COALESCE(contact.rec_id, 0) as rec_id,
    COALESCE(contact.first_name, '') as first_name,
    COALESCE(contact.last_name, '') as last_name,
    COALESCE(contact.full_name, '') as full_name,
    COALESCE(contact.prefix, '') as prefix,
    COALESCE(contact.email, '') as email,
    COALESCE(contact.phone_number, '') as phone_number,
    COALESCE(contact.phone_number2, '') as phone_number2,
    COALESCE(contact.mobile_phone, '') as mobile_phone,
    COALESCE(contact.work_phone, '') as work_phone,
    COALESCE(contact.home_phone, '') as home_phone,
    COALESCE(contact.fax_number, '') as fax_number,
    COALESCE(contact.address1, '') as address1,
    COALESCE(contact.city, '') as city,
    COALESCE(contact.state, '') as state,
    COALESCE(contact.zip_code, '') as zip_code,
    COALESCE(contact.country, '') as country,
    COALESCE(contact.date_of_birth, '') as date_of_birth,
    COALESCE(contact.gender, '') as gender,
    COALESCE(contact.marital_status, '') as marital_status,
    COALESCE(contact.occupation, '') as occupation,
    COALESCE(contact.company_name, '') as company_name,
    COALESCE(contact.job_title, '') as job_title,
    COALESCE(contact.contact_type, '') as contact_type,
    COALESCE(contact.status, 'Active') as contact_status,
    COALESCE(contact.assigned_to, 0) as assigned_to,
    COALESCE(contact.rec_add, '') as rec_add,
    COALESCE(contact.rec_edit, '') as rec_edit,
    CAST(processing_time AS STRING) as processing_timestamp,
    DATE_FORMAT(processing_time, 'yyyy-MM-dd') as processing_date
FROM redtail_contact_raw_input
CROSS JOIN UNNEST(records) AS contact;
